### ISSUE TITLE
Good source collection

### ISSUE THREAD

**Issue by EagleEyeLogic** [Standecco/ROKerbalism#18]
I noticed the progress of your good work.

After reading some changes I think it's a good idea to collect the sources here and find out what we will use.

So I start with the first question

we want ~0.001 rad/h at Earth????
Maybe not relevant, but this means only 12years on earth surface and you have the allowed lifetime radiation for NASA astronauts.

For my knowlege we have 0.35mSv / year as part of natural cosmic radiation.

This is 0.035 rad / year.

Don't want to stay on KSC for so long, but people may play with lifetime radiation on and Kerbalism simulate a lot of 0 behind the ,

**Comment by Standecco** [comment]
What I've found, and tried to reproduce, is 1-0.9 mSv/day in LEO at solar minimum, and half of that (~0.4 mSv/day) at solar maximum. More than 80% of the organ dose equivalent comes from GRC, while the rest is from the sun. This is what we should probably check against (source n.2):
![image](https://user-images.githubusercontent.com/43384369/65321514-b1770e80-dba4-11e9-8fde-5a48b883876c.png)


A list of sources:
1. [Good summary of radiation risks and mission days](https://www.nasa.gov/pdf/214661main_1015-Cucinotta_3rdExp-Conf.pdf)
2. [With its references, probably the best summary of radiation doses received on various occasions](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20070010704.pdf)
3. [Huge paper about radiation shielding](https://www.dartmouth.edu/~sshepherd/research/Shielding/docs/NASA-97-cp3360.pdf) (first reference in n.2)
4. [Paper exploring the possibility and feasibility of active shielding for manned spacecrafts](https://www.researchgate.net/publication/325285302_Can_artificial_miniature_magnetospheres_be_used_to_protect_spacecraft)

I have even more sources, so I'm going to expand the list in the future. The current model is probably too optimistic; career limit should probably be lowered from the 3 Sv they're at (career limit for a >50y astronaut) to an average of the male and female career limit, possibly a weighted mean for all the astronauts that have ever flown. 
I'm assuming that people have lifetime radiation on, since having it off is clearly unrealistic; not sure if there's a way to set that on by default.

**Comment by EagleEyeLogic** [comment]
Will read the sources this weekend.

3Sv is ok for now. If this is reached, people die ingame
