### ISSUE TITLE
Zond 7K-L1 CO2 Scrubber not working

### ISSUE THREAD

**Issue by YuryRugayn** [Standecco/ROKerbalism#20]
Zond 7K-L1 from RN-SovietSpacecraft CO2 Scrubber not working

**Comment by Standecco** [comment]
Could you give a little more info? What is the name of the part, and why is it not working? Is it missing completely, or not scrubbing enough, or just not activating?

**Comment by YuryRugayn** [comment]
TY for prompt reply.
I'll try to give more info: Part -  Zond 7K-L1 capsule, from Rider Nick SovietSpacecraft mod. 
On part management dropout tab scrubber appear to be running. CO2 Tank for the capsule remain at 0 amount. After several orbits crue get increased CO2 poisoning and death
Beforehand on Kerbalism warning Background processes was uninstalled (not shure if it related or no)

**Comment by Standecco** [comment]
I'll need you to perform a few tests, since I can't do them myself at the moment:

First, don't check the CO2 tanks in the resources tab, those are not indicative of the internal composition of the cabin's atmosphere. You should watch for the "co2 level" indicator in the kerbalism "INFO" tab, in the habitat section:
![image](https://user-images.githubusercontent.com/43384369/65490507-93175880-dead-11e9-8e05-6cd9f99349ac.png)
Then, you should test if the CO2 level also rises with less crew (down to 1), and if it rises any slower with the scrubber active rather than off. 
Lastly (but you should probably do this first), can you check what type of scrubber the Zond has? In the "Configure life support" button in the editor PAW you should have its name and characteristics. It should be KO2 scrubber, in which case you also need to include KO2, potassium superoxide, in the capsule. A screenshot of that window would be ideal.

**Comment by YuryRugayn** [comment]
Resolved: no potassium superoxide was loaded by default in capsule for KO2, no LiOH for Li scrubber in orbital module and no nitrogen fo pressure control as well. Should be loaded manually, replacing CO2 tanks
