### ISSUE TITLE
No hab pressure for the mk1-3 and apollo cm

### ISSUE THREAD

**Issue by aihaw** [Standecco/ROKerbalism#47]
Hi! Playing under RP-1 in 1.8, I can't find any way to activate N2 or O2 pressure control system on those command modules. I believe it is expected that we use the ROcapsule apollo service module as the life support system, which I don't like as I want to stay stock-ish without "UNITED STATES" written on my vessel. I'm not really familiar with editing config parts, so I'm asking please how can I add the N2 pressure module to the mk1-2 command pod? Thank you in advance!

**Comment by Standecco** [comment]
You're correct, you're supposed to use the service module; but if you want to build one yourself, you shouldn't need to edit any config. The external life support module part should give you the option to add any pressure controller you like. Just be sure to download the master branch and use that since I noticed some tech unlocks were wrong, and that you'd get the controllers much later than you should've.
