### ISSUE TITLE
EC consumption simulation ignores avionics shutdown

### ISSUE THREAD

**Issue by todi** [Standecco/ROKerbalism#9]
I have a probe in orbit around the Moon with an "Early Controllable Core". In flight, controlling the probe, Kerbalism reports about 2 days of EC remaining. Clicking "Shutdown Avionics" on the probe core changes this to 113days, as expected. When I then return to the Space Center, Kerbalism again reports about 2 days, ignoring the power draw reduction from 50W to 1W.

This is with current master for RO, RP-1 and ROKerbalism.

**Comment by Standecco** [comment]
So the probe actually draws all its EC in 2 days while unloaded? That would be because Kerbalism has no idea that the module has 2 possible modes, and while unloaded it assumes to be the active one. @SirMortimer any idea?

**Comment by todi** [comment]
Yes, if I time warp the 2 days ahead all EC is gone.

**Comment by Standecco** [comment]
It will need custom code then, it's going to take a while.

**Comment by gotmachine** [comment]
Gave a quick look at the issue. The proceduralavionics module is patching the stock modulecommand reshandler at runtime. Since we use the prefab values, we can't see those changes. Fixing that would require explicit background processing support for the module : 
- read the persisted systemEnabled bool 
- patch the modulecommand ec rate according to the proceduralavionics prefab enabledkW/disabledkW rate.

**Comment by Gordon-Dry** [comment]
Already in VAB the planner does not make any difference if the avionics are shut down or not.
(There is a PAW button "Shutdown Avionics")

**Comment by DRVeyl** [comment]
This should be fixed in the commits to RP-1 master (which controls avionics) merged on/around 31 DEC 2019.

**Comment by Standecco** [comment]
definitely fixed
